// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ bcdc1024a90ff98098c4db979a30da47c586f8ec
//   Firmware/Libraries/SimGateway/AxisCal.h (calibration wire contract)
//   Firmware/Libraries/SimGateway/AxisCal.cpp (payload length table)

/**
 * SimGateway axis-calibration protocol constants. Wire contract:
 * FirmwarePlan/03-uart-usb-hid-protocol.md § Calibration Protocol (USB CDC).
 *
 * The codec in shared/calibration.ts restates these so `src/shared` stays free of a
 * `src/main` import; reference.test.ts asserts the two agree, so a firmware bump fails loudly.
 */
export const CAL_PROTO = {
  /** Protocol version. HELLO_ACK carries this; gate on it, not on the firmware version. */
  version: 1,
  /** Stored-blob layout version, reported by HELLO_ACK as `blobVersion`. */
  blobVersion: 1,
  /** HID report axis slots. Fixed by the descriptor, not by how many a cockpit populates. */
  axisSlots: 8,
  /** Axis-selection sentinel: "all" for RESET, "none" for SESSION_OPEN / STREAM_SELECT. */
  axisNone: 0xff,
  /** magic 4 + type 1 + seq 1 + len 2 + crc 2. */
  envelopeBytes: 10,
  /** CAL_DATA, the largest legal payload — the bound on how much a receiver may buffer. */
  maxPayload: 82,
  /** Frame lead-in "\xAA S K C". Not collision-proof outbound, which is why the CRC is mandatory. */
  magic: [0xaa, 0x53, 0x4b, 0x43]
} as const

export interface CalTypeInfo {
  /** Name as the protocol doc writes it, e.g. `SESSION_OPEN`. */
  name: string
  /** The firmware identifier it came from, e.g. `CAL_T_SESSION_OPEN`. */
  macro: string
  label: string
  /** High bit of the type byte set = device -> client. */
  fromDevice: boolean
  /** The single legal payload length for this type. */
  payloadLen: number
}

/** Message types, keyed by wire type byte — from CalType (AxisCal.h). */
export const CAL_TYPES: Partial<Record<number, CalTypeInfo>> = {
  0x1: { name: 'HELLO', macro: 'CAL_T_HELLO', label: 'Hello', fromDevice: false, payloadLen: 0 },
  0x2: {
    name: 'GET_CAL',
    macro: 'CAL_T_GET_CAL',
    label: 'Get cal',
    fromDevice: false,
    payloadLen: 0
  },
  0x3: {
    name: 'SESSION_OPEN',
    macro: 'CAL_T_SESSION_OPEN',
    label: 'Session open',
    fromDevice: false,
    payloadLen: 1
  },
  0x4: {
    name: 'SESSION_CLOSE',
    macro: 'CAL_T_SESSION_CLOSE',
    label: 'Session close',
    fromDevice: false,
    payloadLen: 0
  },
  0x5: { name: 'COMMIT', macro: 'CAL_T_COMMIT', label: 'Commit', fromDevice: false, payloadLen: 9 },
  0x6: { name: 'RESET', macro: 'CAL_T_RESET', label: 'Reset', fromDevice: false, payloadLen: 1 },
  0x7: {
    name: 'KEEPALIVE',
    macro: 'CAL_T_KEEPALIVE',
    label: 'Keepalive',
    fromDevice: false,
    payloadLen: 0
  },
  0x8: {
    name: 'STREAM_SELECT',
    macro: 'CAL_T_STREAM_SELECT',
    label: 'Stream select',
    fromDevice: false,
    payloadLen: 1
  },
  0x81: {
    name: 'HELLO_ACK',
    macro: 'CAL_T_HELLO_ACK',
    label: 'Hello ack',
    fromDevice: true,
    payloadLen: 6
  },
  0x82: {
    name: 'CAL_DATA',
    macro: 'CAL_T_CAL_DATA',
    label: 'Cal data',
    fromDevice: true,
    payloadLen: 82
  },
  0x83: {
    name: 'SESSION_ACK',
    macro: 'CAL_T_SESSION_ACK',
    label: 'Session ack',
    fromDevice: true,
    payloadLen: 5
  },
  0x84: { name: 'ACK', macro: 'CAL_T_ACK', label: 'Ack', fromDevice: true, payloadLen: 1 },
  0x85: { name: 'NACK', macro: 'CAL_T_NACK', label: 'Nack', fromDevice: true, payloadLen: 3 },
  0x86: { name: 'RAW', macro: 'CAL_T_RAW', label: 'Raw', fromDevice: true, payloadLen: 5 }
} as const

export interface CalNackInfo {
  name: string
  macro: string
  label: string
}

/**
 * NACK reasons, keyed by wire reason byte — from CalNackReason (AxisCal.h).
 *
 * Partial: three of these cannot reach a client. BAD_CRC and BAD_LENGTH are rejected at the
 * framing layer, where a failing candidate is not a frame at all and its bytes are relayed
 * instead of answered; BAD_TYPE likewise, so the gateway's `default:` arm is unreachable from
 * the wire. A protocol mismatch therefore surfaces as a timeout on HELLO, never as a NACK.
 */
export const CAL_NACK_REASONS: Partial<Record<number, CalNackInfo>> = {
  0x1: { name: 'BAD_CRC', macro: 'CAL_NACK_BAD_CRC', label: 'Bad crc' },
  0x2: { name: 'BAD_LENGTH', macro: 'CAL_NACK_BAD_LENGTH', label: 'Bad length' },
  0x3: { name: 'BAD_TYPE', macro: 'CAL_NACK_BAD_TYPE', label: 'Bad type' },
  0x4: { name: 'BAD_INDEX', macro: 'CAL_NACK_BAD_INDEX', label: 'Bad index' },
  0x5: { name: 'BAD_ORDER', macro: 'CAL_NACK_BAD_ORDER', label: 'Bad order' },
  0x6: { name: 'NO_SESSION', macro: 'CAL_NACK_NO_SESSION', label: 'No session' },
  0x7: { name: 'NO_STORAGE', macro: 'CAL_NACK_NO_STORAGE', label: 'No storage' },
  0x8: { name: 'BAD_DEADZONE', macro: 'CAL_NACK_BAD_DEADZONE', label: 'Bad deadzone' }
} as const

/**
 * type byte -> its one legal payload length.
 *
 * Checked BEFORE the payload is buffered. LEN is read before the CRC can be verified, so on a
 * false frame it is noise — a stray magic in DCS-BIOS text can decode a LEN near 65535, and a
 * receiver that waits for that many bytes stalls its line assembly.
 */
export const CAL_PAYLOAD_LEN: Partial<Record<number, number>> = {
  0x1: 0,
  0x2: 0,
  0x3: 1,
  0x4: 0,
  0x5: 9,
  0x6: 1,
  0x7: 0,
  0x8: 1,
  0x81: 6,
  0x82: 82,
  0x83: 5,
  0x84: 1,
  0x85: 3,
  0x86: 5
} as const
