// Hand-curated — NOT generated by `npm run sync`.
//
// The DCS-BIOS "common data" / metadata module (the cross-aircraft block that
// carries _ACFT_NAME) is not vendored in the OpenSkyhawk firmware repo, so there
// is no upstream file to sync. These constants come from the DCS-BIOS common
// metadata definition (see PRD.md §12) and change only with DCS-BIOS itself.

/** Live aircraft module name, exported by DCS-BIOS at a fixed cross-module address. */
export const ACFT_NAME = {
  /** DCS-BIOS export address of the _ACFT_NAME string. */
  address: 0x0000,
  /** Null-terminated, max 24 bytes. Empty / "NONE" when no module is loaded. */
  maxLength: 24
} as const

/**
 * Address window the A-4E-C module exports into. Used to *infer* "A-4E-C" when
 * _ACFT_NAME is unavailable, and to gate named decoding (raw-only outside it).
 */
export const A4EC_ADDRESS_RANGE = { start: 0x8400, end: 0x8554 } as const
