// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ 51f150f793c5b10b161bc06d587e4778fed60263
//   Firmware/Libraries/HIDControls/HIDControls.h (9 controls)

export interface HidControl {
  /** CAN controlId (0x0010–0x00FF). NOT a USB-report index. */
  id: number
  macro: string
  label: string
  comment: string
}

export const HID_CONTROLS: readonly HidControl[] = [
  {
    id: 0x10,
    macro: 'CTRL_ROLL',
    label: 'Roll',
    comment: 'Roll axis       — stick sub-node (AS5600 / pot)'
  },
  {
    id: 0x11,
    macro: 'CTRL_PITCH',
    label: 'Pitch',
    comment: 'Pitch axis      — stick sub-node (AS5600 / pot)'
  },
  {
    id: 0x12,
    macro: 'CTRL_THROTTLE',
    label: 'Throttle',
    comment: 'Throttle lever  — throttle sub-node (ADC)'
  },
  {
    id: 0x13,
    macro: 'CTRL_RUDDER',
    label: 'Rudder',
    comment: 'Rudder axis     — pedal sub-node (ADC)'
  },
  {
    id: 0x14,
    macro: 'CTRL_BRAKE_L',
    label: 'Brake L',
    comment: 'Left toe brake  — pedal sub-node (ADC)'
  },
  {
    id: 0x15,
    macro: 'CTRL_BRAKE_R',
    label: 'Brake R',
    comment: 'Right toe brake — pedal sub-node (ADC)'
  },
  {
    id: 0x16,
    macro: 'CTRL_ZOOM',
    label: 'Zoom',
    comment: 'Zoom axis       — throttle sub-node (ADC)'
  },
  {
    id: 0x20,
    macro: 'CTRL_HAT_0',
    label: 'Hat 0',
    comment: 'Hat switch 0    — stick grip (4-way / 8-way)'
  },
  {
    id: 0x30,
    macro: 'CTRL_TRIGGER',
    label: 'Trigger',
    comment: 'Trigger (button index 0) — stick grip'
  }
]

/** controlId routing ranges + sentinels, mirrored from HIDControls.h. */
export const HID_ID = {
  AXIS_MIN: 0x10,
  AXIS_MAX: 0x1f,
  HAT_MIN: 0x20,
  HAT_MAX: 0x2f,
  BUTTON_MIN: 0x30,
  BUTTON_MAX: 0xaf,
  HID_MIN: 0x10,
  HID_MAX: 0xff
} as const

export const HID_CONTROLS_BY_ID: ReadonlyMap<number, HidControl> = new Map(
  HID_CONTROLS.map((c) => [c.id, c])
)
