// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ 19245eafe3ecdbfcbe3a9ab12bb60f8ceb10f748
//   Firmware/Libraries/SimGateway/SimGateway.cpp (HIDReport struct + descriptor)

/**
 * Fixed 34-byte SimGateway HID report. Asserted against the firmware struct at
 * sync time, so a layout change fails `npm run sync` loudly.
 *
 * Semantics from the USB HID descriptor (NB: differ from the CAN controlId space):
 *  - axes are SIGNED int16, little-endian, logical range −32768..32767 (no 0x8000 bias).
 *  - hat nibbles encode 0..7 = N/NE/E/SE/S/SW/W/NW; value ≥ 8 (e.g. 0xF) = null/centered.
 */
export const HID_REPORT_LAYOUT = {
  size: 34,
  buttons: { offset: 0, bytes: 16, count: 128 },
  hats: {
    offset: 16,
    bytes: 2,
    count: 4,
    nibbleBits: 4,
    /** Decoded value ≥ this is the centered/null state. */
    centeredAtOrAbove: 8,
    nullNibble: 0xf
  },
  axes: {
    offset: 18,
    bytes: 16,
    count: 8,
    signed: true,
    min: -32768,
    max: 32767,
    usages: ['X', 'Y', 'Z', 'Rx', 'Ry', 'Rz', 'Slider', 'Dial']
  }
} as const
