// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ b31bed1698cab5e5760aeef27669e9852320db18
//   Firmware/Libraries/HIDControls/HIDControls.h (NODE_STATUS contract v1)

/**
 * Reserved DCS-BIOS identifiers for PanelBridge node-status reporting (#86).
 * The decoder in shared/nodes.ts is written for protoVersion; reference.test.ts
 * asserts this matches SUPPORTED_NODE_PROTO so a firmware bump fails loudly.
 */
export const NODE_STATUS = {
  protoVersion: 1,
  reqAddress: 0x86fe,
  msgName: '_NODE_STATUS',
  endMsgName: '_NODE_STATUS_END'
} as const
