// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ b31bed1698cab5e5760aeef27669e9852320db18
//   Firmware/NODE_IDS.md (2 entries)

/** CAN NODE_ID -> panel group name, from the firmware NODE_IDS.md registry. */
export const NODE_NAMES: Record<number, { name: string; console: string }> = {
  0: { name: 'PanelBridge', console: '—' },
  1: { name: 'Center_Armament', console: 'Center' }
}
