// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ bcdc1024a90ff98098c4db979a30da47c586f8ec
//   Firmware/NODE_IDS.md (3 entries)

/** CAN NODE_ID -> panel group name, from the firmware NODE_IDS.md registry. */
export const NODE_NAMES: Record<number, { name: string; console: string }> = {
  0: { name: 'PanelBridge', console: '—' },
  1: { name: 'Center_Armament', console: 'Center' },
  2: { name: 'Right_Navigation', console: 'Right' }
}
