// AUTO-GENERATED by `npm run sync` (scripts/sync-a4ec.ts) — DO NOT EDIT.
// Source: https://github.com/OpenSkyhawk/OpenSkyhawk.git @ 19245eafe3ecdbfcbe3a9ab12bb60f8ceb10f748
//   Firmware/Libraries/NodeStatus/NodeStatus.h (NODE_STATUS contract v2)

/**
 * Reserved DCS-BIOS identifiers for PanelBridge node-status reporting (#86).
 * The decoder in shared/nodes.ts is written for protoVersion; reference.test.ts
 * asserts this matches SUPPORTED_NODE_PROTO so a firmware bump fails loudly.
 */
export const NODE_STATUS = {
  protoVersion: 2,
  reqAddress: 0x86fe,
  msgName: '_NODE_STATUS',
  endMsgName: '_NODE_STATUS_END'
} as const

/** HEALTH_n `flags` bits — from NodeHealthFlag (NodeStatus.h). Decoder masks against these. */
export const NODE_HEALTH_FLAGS = {
  OVERHEAT: 0x1,
  DEGRADED: 0x2
} as const

/**
 * HEALTH_n `faultId` dictionary — from NodeFaultCode (NodeStatus.h). id -> human label
 * (SkyHawkClient#40 render) + the firmware comment as a description. `label` is derived from
 * the enum name; `description` is verbatim from the header. Append-only, mirrors the firmware.
 */
export const NODE_FAULT_CODES: Record<
  number,
  { name: string; label: string; description: string }
> = {
  0: { name: 'NONE', label: 'None', description: '' },
  1: {
    name: 'I2C_PERIPHERAL',
    label: 'I2C peripheral',
    description: 'an I2C device (OLED/mux/expander) tripped its I2cHealth breaker'
  },
  2: { name: 'OVER_VOLTAGE', label: 'Over voltage', description: 'rail over-voltage (PDU)' },
  3: { name: 'UNDER_VOLTAGE', label: 'Under voltage', description: 'rail under-voltage (PDU)' },
  4: {
    name: 'SHORT_CIRCUIT',
    label: 'Short circuit',
    description: 'rail short / over-current (PDU)'
  },
  5: {
    name: 'HOST_LINK_LOST',
    label: 'Host link lost',
    description: 'PanelBridge lost the host serial link'
  }
} as const
